# Generated by Django 3.2 on 2021-06-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210529_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='datetime_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
